blueprint:
  name: LK Wiser 4-knaps – gardin og lys (ZHA)
  description: >
    Styr gardin med øverste knapper (tryk = kør, tryk igen = stop) og lys med nederste knapper
    (tænd/sluk + hold for dim op/ned) for LK Wiser 4-knaps batteritryk via ZHA.
  domain: automation
  author: SigNoget
  source_url: https://github.com/SigNoget/HomeAssistant/blob/main/lk-wiser-batteritryk.yaml

  input:
    zigbee_device:
      name: LK Wiser 4-knaps tryk (ZHA)
      description: Vælg dit LK Wiser batteritryk (ZHA-enhed).
      selector:
        device:
          integration: zha
          manufacturer: Schneider Electric

    cover_entity:
      name: Gardin
      description: Gardin/cover der styres af de øverste knapper.
      selector:
        entity:
          domain: cover

    light_entity:
      name: Lys
      description: Lys der styres af de nederste knapper.
      selector:
        entity:
          domain: light

    brightness_step_up:
      name: Dimming op – step-størrelse
      description: >
        Hvor meget lysstyrken ændres pr. dim-trin når der dæmpes op.
        Ca. 50–80 er normalt. Højere = hurtigere dim.
      default: 60
      selector:
        number:
          min: 1
          max: 255
          mode: box

    brightness_step_down:
      name: Dimming ned – step-størrelse
      description: >
        Hvor meget lysstyrken ændres pr. dim-trin når der dæmpes ned.
        Ca. 50–80 er normalt. Højere = hurtigere dim.
      default: 60
      selector:
        number:
          min: 1
          max: 255
          mode: box

    transition_time:
      name: Transitiontid for dimming
      description: >
        Hvor glidende dimming skal være (i sekunder).
        Lav værdi = hurtig/reaktiv, høj værdi = mere glidende.
      default: 0.5
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          mode: box

    debug_mode:
      name: Debug-log
      description: >
        Hvis aktiveret, logger automations-trigger events til logbook/service_log for fejlfinding.
      default: false
      selector:
        boolean: {}

mode: restart
max_exceeded: silent

variables:
  v_debug: !input debug_mode
  v_cover: !input cover_entity
  v_light: !input light_entity
  v_step_up: !input brightness_step_up
  v_step_down: !input brightness_step_down
  v_transition: !input transition_time

  v_command: >
    {{ trigger.event.data.command if trigger is not none else '' }}
  v_endpoint: >
    {{ trigger.event.data.endpoint_id if trigger is not none else 0 }}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zigbee_device

action:
  - if:
      - condition: template
        value_template: "{{ v_debug }}"
    then:
      - service: logbook.log
        data:
          name: "LK Wiser 4-knaps"
          message: >
            Triggered with endpoint={{ v_endpoint }}, command={{ v_command }},
            args={{ trigger.event.data.args }}
          entity_id: "{{ v_light }}"

  - choose:

      # -------------------------------------------------------------------
      # ØVERSTE KNAPPER – GARDIN (endpoint 21, on/off)
      # -------------------------------------------------------------------

      # Top venstre: ÅBN / STOP
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 21 and v_command == 'on' }}
        sequence:
          - choose:
              # Hvis gardin allerede bevæger sig → STOP
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "opening"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: "{{ v_cover }}"
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "closing"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: "{{ v_cover }}"
            default:
              # Ellers: start med at åbne
              - service: cover.open_cover
                target:
                  entity_id: "{{ v_cover }}"

      # Top højre: LUK / STOP
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 21 and v_command == 'off' }}
        sequence:
          - choose:
              # Hvis gardin allerede bevæger sig → STOP
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "opening"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: "{{ v_cover }}"
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "closing"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: "{{ v_cover }}"
            default:
              # Ellers: start med at lukke
              - service: cover.close_cover
                target:
                  entity_id: "{{ v_cover }}"

      # -------------------------------------------------------------------
      # NEDERSTE KNAPPER – LYS (endpoint 22, on/off/move/stop)
      # -------------------------------------------------------------------

      # Nederste venstre kort tryk: TÆND
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 22 and v_command == 'on' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ v_light }}"

      # Nederste højre kort tryk: SLUK
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 22 and v_command == 'off' }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ v_light }}"

      # Nederste venstre HOLD: DIM OP (move_with_on_off)
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 22 and v_command == 'move_with_on_off' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ v_light }}"
            data:
              brightness_step: "{{ v_step_up | int }}"
              transition: "{{ v_transition | float }}"

      # Nederste højre HOLD: DIM NED (move)
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 22 and v_command == 'move' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ v_light }}"
            data:
              brightness_step: "-{{ v_step_down | int }}"
              transition: "{{ v_transition | float }}"

      # SLIP: STOP DIM
      - conditions:
          - condition: template
            value_template: >
              {{ v_endpoint == 22 and v_command == 'stop' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ v_light }}"
            data:
              brightness_step: 0
              transition: 0


  # Ingen default: andre commands ignoreres
