blueprint:
  name: LK Wiser 4-knaps – gardin + glidende lysdimming (ZHA)
  description: >
    Version 0.8.2: 2026-01-07 07:39  
    Styr gardin med øverste knapper (tryk = kør, tryk igen = stop)
    og lys med nederste knapper (tænd/sluk + glidende dim op/ned ved hold).
  domain: automation
  author: SigNoget
  source_url: https://github.com/SigNoget/HomeAssistant/lk-wiser-batteritryk.yaml

  input:
    zigbee_device:
      name: LK Wiser 4-knaps tryk (ZHA)
      description: Vælg dit LK Wiser batteritryk.
      selector:
        device:
          integration: zha
          manufacturer: Schneider Electric

    cover_entity:
      name: Gardin
      description: Gardin/cover der styres af de øverste knapper.
      selector:
        entity:
          domain: cover

    light_entity:
      name: Lys
      description: Lys der styres af de nederste knapper.
      selector:
        entity:
          domain: light

    brightness_step_up:
      name: Dimming op – step-størrelse
      description: >
        Hvor meget lysstyrken ændres pr. loop når der dæmpes op.
        1–5 giver glidende dimming. 3 anbefales.
      default: 3
      selector:
        number:
          min: 1
          max: 10
          mode: box

    brightness_step_down:
      name: Dimming ned – step-størrelse
      description: >
        Hvor meget lysstyrken ændres pr. loop når der dæmpes ned.
        1–5 giver glidende dimming. 3 anbefales.
      default: 3
      selector:
        number:
          min: 1
          max: 10
          mode: box

    debug_mode:
      name: Debug-log
      default: false
      selector:
        boolean: {}

mode: restart
max_exceeded: silent

variables:
  v_debug: !input debug_mode
  v_cover: !input cover_entity
  v_light: !input light_entity
  v_step_up: !input brightness_step_up
  v_step_down: !input brightness_step_down

  v_command: >
    {{ trigger.event.data.command if trigger is not none else '' }}
  v_endpoint: >
    {{ trigger.event.data.endpoint_id if trigger is not none else 0 }}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zigbee_device

action:
  - if:
      - condition: template
        value_template: "{{ v_debug }}"
    then:
      - service: logbook.log
        data:
          name: "LK Wiser 4-knaps"
          message: >
            Triggered with endpoint={{ v_endpoint }}, command={{ v_command }},
            args={{ trigger.event.data.args }}
          entity_id: "{{ v_light }}"

  - choose:

      # ---------------------------------------------------------
      # ØVERSTE KNAPPER – GARDIN (endpoint 21)
      # ---------------------------------------------------------

      # Top venstre: ÅBN / STOP
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 21 and v_command == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "opening"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: !input cover_entity

              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "closing"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: !input cover_entity

            default:
              - service: cover.open_cover
                target:
                  entity_id: !input cover_entity

      # Top højre: LUK / STOP
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 21 and v_command == 'off' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "opening"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: !input cover_entity

              - conditions:
                  - condition: state
                    entity_id: !input cover_entity
                    state: "closing"
                sequence:
                  - service: cover.stop_cover
                    target:
                      entity_id: !input cover_entity

            default:
              - service: cover.close_cover
                target:
                  entity_id: !input cover_entity


      # ---------------------------------------------------------
      # NEDERSTE KNAPPER – GLIDENDE DIMMING (endpoint 22)
      # ---------------------------------------------------------

      # TÆND (kort tryk)
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 22 and v_command == 'on' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: "{{ v_light }}" }

      # SLUK (kort tryk)
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 22 and v_command == 'off' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: "{{ v_light }}" }

      # DIM OP (hold) – move_with_on_off
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 22 and v_command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: "{{ v_light }}" }
                  data:
                    brightness_step: "{{ v_step_up | int }}"
                    transition: 0
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input zigbee_device
                        endpoint_id: 22
                        command: "stop"
                  timeout: "00:00:0.05"
                  continue_on_timeout: true

      # DIM NED (hold) – move
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 22 and v_command == 'move' }}"
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: "{{ v_light }}" }
                  data:
                    brightness_step: "{{ -(v_step_down | int) }}"
                    transition: 0
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input zigbee_device
                        endpoint_id: 22
                        command: "stop"
                  timeout: "00:00:0.05"
                  continue_on_timeout: true

      # STOP DIM
      - conditions:
          - condition: template
            value_template: "{{ v_endpoint == 22 and v_command == 'stop' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: "{{ v_light }}" }
            data:
              brightness_step: 0
              transition: 0

# ---------------------------------------------------------
# Blueprint version: 2026-01-07 07:39
# ---------------------------------------------------------
